"""empty message

Revision ID: eb63b4d4a112
Revises: fa1f454b6dc2
Create Date: 2021-06-21 15:08:32.966704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb63b4d4a112'
down_revision = 'fa1f454b6dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'request', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'user_id')
    # ### end Alembic commands ###
