version: "3.0"
services:
  db:
    image: postgres
    restart: always
    env_file:
      - db/database.conf
    volumes:
      - db_volume:/var/lib/postgresql
    ports:
    - "5437:5432"
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"
  app:
    build: .
    volumes:
    - ./app:/app
    env_file:
      - db/database.conf
    links:
      - db
      - rabbitmq
  app2:
    build:
      context: .
      dockerfile: docker-containers/app_two/Dockerfile
    volumes:
      - ./app2:/app
    links:
      - rabbitmq
  nginx:
    image: nginx
    volumes:
      - ./nginx/flask.conf:/etc/nginx/conf.d/flask.conf
      - ./nginx/flask_two.conf:/etc/nginx/conf.d/flask_two.conf
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - app
      - app2
  adminer:
    image: adminer
    ports:
      - "8090:8080"
    links:
      - db
  react:
    build: 
      context: .
      dockerfile: docker-containers/frontend/Dockerfile
    volumes: 
      - ./frontend:/app
    ports:
      - "8877:3000"
    depends_on: 
      - app
      - app2
volumes:
  db_volume: